-- Supabase schema for Todo / Ежедневник

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  nickname text unique not null,
  theme text default 'light',
  created_at timestamptz default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  name text not null
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  category_id bigint references public.categories(id) on delete set null,
  title text not null,
  time time not null,
  repeat boolean default false,
  days int[] default '{}',
  task_date date,
  description text,
  priority text,
  created_at timestamptz default now()
);

create table if not exists public.task_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete cascade,
  date date not null,
  status text not null,
  created_at timestamptz default now()
);

create table if not exists public.settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  notifications boolean default false,
  theme text default 'light'
);

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.tasks enable row level security;
alter table public.task_logs enable row level security;
alter table public.settings enable row level security;

create policy "Users can view own profile" on public.users
  for select using (auth.uid() = id);

create policy "Users can insert own profile" on public.users
  for insert with check (auth.uid() = id);

create policy "Users can update own profile" on public.users
  for update using (auth.uid() = id);

create policy "Users can delete own profile" on public.users
  for delete using (auth.uid() = id);

create policy "Users manage own categories" on public.categories
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users manage own tasks" on public.tasks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users manage own logs" on public.task_logs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users manage own settings" on public.settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
